export const roles = {
    ROLE_CUSTOMER: 'ROLE_CUSTOMER',
    ROLE_BOSS: 'ROLE_BOSS',
    ROLE_HEADTRAN: 'ROLE_HEADTRAN',
    ROLE_HEADCOL: 'ROLE_HEADCOL',
    ROLE_OFFICERTRAN: 'ROLE_OFFICERTRAN',
    ROLE_OFFICERCOL: 'ROLE_OFFICERCOL',
}